name = "memos-worker"
compatibility_date = "2025-08-19"
main = "src/index.js"
[assets]
directory = "./src/public"
run_worker_first = [
	"/api/*"
]

[[d1_databases]]
binding = "DB"
database_id = "7217dfa5-8831-4193-9ffa-60284d9624bb"
database_name = "notes-db"

[[kv_namespaces]]
binding = "NOTES_KV"
id = "54c812c6ae44418d8e9a9d7133a2ae48"
preview_id = ""

[[r2_buckets]]
binding = "NOTES_R2_BUCKET"
bucket_name = "notes-r2-bucket"
preview_bucket_name = "notes-files-preview"
